# Generated by Django 4.2.30 on 2026-07-14 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unitstructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_posted_strength', models.PositiveIntegerField(default=0)),
                ('present', models.PositiveIntegerField(default=0)),
                ('leave', models.PositiveIntegerField(default=0)),
                ('temporary_duty', models.PositiveIntegerField(default=0, verbose_name='Temporary Duty')),
                ('course', models.PositiveIntegerField(default=0)),
                ('hospital_sick', models.PositiveIntegerField(default=0, verbose_name='Hospital / Sick')),
                ('attached_out', models.PositiveIntegerField(default=0)),
                ('other_absence', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_strengths', to='unitstructure.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Strength Return',
                'verbose_name_plural': 'Daily Strength Returns',
                'ordering': ['-date', 'company__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailystrength',
            constraint=models.UniqueConstraint(fields=('date', 'company'), name='unique_strength_per_company_per_day'),
        ),
    ]
