# Generated by Django 4.2.30 on 2026-07-14 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unitstructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('army_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Army / Service Number')),
                ('rank', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_joining_unit', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LEAVE', 'Leave'), ('TD', 'Temporary Duty'), ('COURSE', 'Course'), ('HOSPITAL', 'Hospital / Sick'), ('ATTACHED_OUT', 'Attached Out'), ('OTHER', 'Other')], default='PRESENT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick when a person permanently leaves the unit (posted out / discharged / retired).')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='unitstructure.appointment', verbose_name='Appointment / Trade')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='unitstructure.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('platoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='unitstructure.platoon')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='unitstructure.section')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['company__name', 'rank', 'full_name'],
            },
        ),
    ]
