# Generated by Django 4.2.30 on 2026-07-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('LEAVE', 'Leave'), ('TD', 'Temporary Duty'), ('COURSE', 'Course'), ('HOSPITAL', 'Hospital / Sick'), ('ATTACHMENT', 'Attachment'), ('OTHER', 'Other')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('authority_reference', models.CharField(help_text='e.g. sanction letter number, competent authority approving the absence.', max_length=200, verbose_name='Authority / Reference')),
                ('destination', models.CharField(blank=True, help_text='Non-sensitive administrative reference only (e.g. Home Town, Command Hospital). Do NOT enter operational locations.', max_length=150, verbose_name='Destination / Place')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Leave / TD / Absence Record',
                'verbose_name_plural': 'Leave / TD / Absence Records',
                'ordering': ['-from_date'],
            },
        ),
    ]
