# Generated by Django 4.2.30 on 2026-07-14 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unitstructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duty_date', models.DateField()),
                ('duty_type', models.CharField(help_text='e.g. Quarter Guard, Orderly Officer/NCO, Fire Picket, Fatigue, Kitchen Duty.', max_length=100)),
                ('duty_location', models.CharField(help_text='Generic administrative description only (e.g. "Unit Lines", "Quarter Guard"). Do NOT enter operational deployment locations.', max_length=150, verbose_name='Duty Location / Post')),
                ('shift_time', models.CharField(help_text='e.g. 0600-1400 hrs', max_length=100, verbose_name='Shift / Time')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_rosters', to='unitstructure.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnel_detailed', models.ManyToManyField(related_name='duty_assignments', to='personnel.personnel')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duty Roster Entry',
                'verbose_name_plural': 'Duty Roster Entries',
                'ordering': ['-duty_date', 'company__name'],
            },
        ),
    ]
